spring.application.name=hollow-cache-agencia
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.metrics.enabled=true
# Porta do servidor (pode ser sobrescrita por SERVER_PORT do ambiente)
server.port=${SERVER_PORT:8080}
